backend:
  name: github
  repo: absolvirefoto-byte/anticariat  # Înlocuiește cu datele tale de GitHub (username/repo)
  branch: main                      # Ramura principală (main sau master)

media_folder: "static/images"       # Unde se salvează imaginile urcate
public_folder: "/images"

collections:
  - name: "produse"
    label: "Cărți Anticariat"
    folder: "content/produse"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nume Carte", name: "nume_carte", widget: "string"}
      - {label: "Nume Autor", name: "nume_autor", widget: "string"}
      - {label: "Preț (Lei)", name: "price", widget: "number", value_type: "float"}
      - label: "Categorie"
        name: "category"
        widget: "select"
        options: ["Beletristică", "Documentar", "SF", "Literatură pentru copii", "Literatură străină", "Cărți de școală"]
      - {label: "Editură", name: "editura", widget: "string"}
      - {label: "Data Tipărire (An)", name: "data_tiparire", widget: "string"}
      - {label: "Număr Pagini", name: "nr_pagini", widget: "number", value_type: "int"}
      - label: "Stare Carte"
        name: "stare"
        widget: "select"
        options:
          - {label: "Foarte Bună (fb)", value: "fb"}
          - {label: "Bună (b)", value: "b"}
          - {label: "Satisfăcătoare (s)", value: "s"}
          - {label: "Îngrijită / Degraded (i)", value: "i"}
      - {label: "Imagine Copertă", name: "image", widget: "image"}